//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `ReliableVoto.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package votacionRM;

/**
 * Helper class for marshaling/unmarshaling ListaVotos.
 **/
public final class ListaVotosHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Voto[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Voto.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Voto[] read(com.zeroc.Ice.InputStream istr)
    {
        final Voto[] v;
        final int len0 = istr.readAndCheckSeqSize(9);
        v = new Voto[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Voto.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Voto[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Voto[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ListaVotosHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Voto[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Voto[] v;
            v = ListaVotosHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
