//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Centralizador.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Votacion;

/** @hidden */
public class _ObserverPrxI extends com.zeroc.Ice._ObjectPrxI implements ObserverPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
