//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `Centralizador.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Votacion;

public interface ReplicadorPrx extends com.zeroc.Ice.ObjectPrx
{
    default void recibirResultados(Resultado[] resultados)
    {
        recibirResultados(resultados, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void recibirResultados(Resultado[] resultados, java.util.Map<String, String> context)
    {
        _iceI_recibirResultadosAsync(resultados, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> recibirResultadosAsync(Resultado[] resultados)
    {
        return _iceI_recibirResultadosAsync(resultados, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> recibirResultadosAsync(Resultado[] resultados, java.util.Map<String, String> context)
    {
        return _iceI_recibirResultadosAsync(resultados, context, false);
    }

    /**
     * @hidden
     * @param iceP_resultados -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_recibirResultadosAsync(Resultado[] iceP_resultados, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "recibirResultados", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ResultadosListHelper.write(ostr, iceP_resultados);
                 }, null);
        return f;
    }

    default void suscribirse(ObserverPrx observer)
    {
        suscribirse(observer, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void suscribirse(ObserverPrx observer, java.util.Map<String, String> context)
    {
        _iceI_suscribirseAsync(observer, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> suscribirseAsync(ObserverPrx observer)
    {
        return _iceI_suscribirseAsync(observer, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> suscribirseAsync(ObserverPrx observer, java.util.Map<String, String> context)
    {
        return _iceI_suscribirseAsync(observer, context, false);
    }

    /**
     * @hidden
     * @param iceP_observer -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_suscribirseAsync(ObserverPrx iceP_observer, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "suscribirse", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_observer);
                 }, null);
        return f;
    }

    default void desuscribirse(ObserverPrx observer)
    {
        desuscribirse(observer, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void desuscribirse(ObserverPrx observer, java.util.Map<String, String> context)
    {
        _iceI_desuscribirseAsync(observer, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> desuscribirseAsync(ObserverPrx observer)
    {
        return _iceI_desuscribirseAsync(observer, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> desuscribirseAsync(ObserverPrx observer, java.util.Map<String, String> context)
    {
        return _iceI_desuscribirseAsync(observer, context, false);
    }

    /**
     * @hidden
     * @param iceP_observer -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_desuscribirseAsync(ObserverPrx iceP_observer, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "desuscribirse", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_observer);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReplicadorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ReplicadorPrx.class, _ReplicadorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReplicadorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ReplicadorPrx.class, _ReplicadorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReplicadorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ReplicadorPrx.class, _ReplicadorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ReplicadorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ReplicadorPrx.class, _ReplicadorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ReplicadorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ReplicadorPrx.class, _ReplicadorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ReplicadorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ReplicadorPrx.class, _ReplicadorPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ReplicadorPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ReplicadorPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ReplicadorPrx ice_adapterId(String newAdapterId)
    {
        return (ReplicadorPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ReplicadorPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ReplicadorPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ReplicadorPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ReplicadorPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ReplicadorPrx ice_invocationTimeout(int newTimeout)
    {
        return (ReplicadorPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ReplicadorPrx ice_connectionCached(boolean newCache)
    {
        return (ReplicadorPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ReplicadorPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ReplicadorPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReplicadorPrx ice_secure(boolean b)
    {
        return (ReplicadorPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ReplicadorPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ReplicadorPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ReplicadorPrx ice_preferSecure(boolean b)
    {
        return (ReplicadorPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ReplicadorPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ReplicadorPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ReplicadorPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ReplicadorPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ReplicadorPrx ice_collocationOptimized(boolean b)
    {
        return (ReplicadorPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ReplicadorPrx ice_twoway()
    {
        return (ReplicadorPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ReplicadorPrx ice_oneway()
    {
        return (ReplicadorPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ReplicadorPrx ice_batchOneway()
    {
        return (ReplicadorPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ReplicadorPrx ice_datagram()
    {
        return (ReplicadorPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ReplicadorPrx ice_batchDatagram()
    {
        return (ReplicadorPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ReplicadorPrx ice_compress(boolean co)
    {
        return (ReplicadorPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ReplicadorPrx ice_timeout(int t)
    {
        return (ReplicadorPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ReplicadorPrx ice_connectionId(String connectionId)
    {
        return (ReplicadorPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ReplicadorPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ReplicadorPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Votacion::Replicador";
    }
}
