//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `Centralizador.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Votacion;

public class Resultado implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int idCandidato;

    public int cantidadVotos;

    public Resultado()
    {
    }

    public Resultado(int idCandidato, int cantidadVotos)
    {
        this.idCandidato = idCandidato;
        this.cantidadVotos = cantidadVotos;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Resultado r = null;
        if(rhs instanceof Resultado)
        {
            r = (Resultado)rhs;
        }

        if(r != null)
        {
            if(this.idCandidato != r.idCandidato)
            {
                return false;
            }
            if(this.cantidadVotos != r.cantidadVotos)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Votacion::Resultado");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idCandidato);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, cantidadVotos);
        return h_;
    }

    public Resultado clone()
    {
        Resultado c = null;
        try
        {
            c = (Resultado)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.idCandidato);
        ostr.writeInt(this.cantidadVotos);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.idCandidato = istr.readInt();
        this.cantidadVotos = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Resultado v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Resultado ice_read(com.zeroc.Ice.InputStream istr)
    {
        Resultado v = new Resultado();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Resultado> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Resultado v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(8);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Resultado> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Resultado.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Resultado _nullMarshalValue = new Resultado();

    /** @hidden */
    public static final long serialVersionUID = -6670049709683700612L;
}
