//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `Elecciones.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Votacion;

/**
 * Helper class for marshaling/unmarshaling CandidatosList.
 **/
public final class CandidatosListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Candidato[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Candidato.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Candidato[] read(com.zeroc.Ice.InputStream istr)
    {
        final Candidato[] v;
        final int len0 = istr.readAndCheckSeqSize(6);
        v = new Candidato[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Candidato.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Candidato[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Candidato[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            CandidatosListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Candidato[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Candidato[] v;
            v = CandidatosListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
