//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `ReliableVoto.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package votacionRM;

public class Voto implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String id;

    public int idCandidato;

    public int idMesa;

    public Voto()
    {
        this.id = "";
    }

    public Voto(String id, int idCandidato, int idMesa)
    {
        this.id = id;
        this.idCandidato = idCandidato;
        this.idMesa = idMesa;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Voto r = null;
        if(rhs instanceof Voto)
        {
            r = (Voto)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                if(this.id == null || r.id == null || !this.id.equals(r.id))
                {
                    return false;
                }
            }
            if(this.idCandidato != r.idCandidato)
            {
                return false;
            }
            if(this.idMesa != r.idMesa)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::votacionRM::Voto");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idCandidato);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idMesa);
        return h_;
    }

    public Voto clone()
    {
        Voto c = null;
        try
        {
            c = (Voto)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.id);
        ostr.writeInt(this.idCandidato);
        ostr.writeInt(this.idMesa);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readString();
        this.idCandidato = istr.readInt();
        this.idMesa = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Voto v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Voto ice_read(com.zeroc.Ice.InputStream istr)
    {
        Voto v = new Voto();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Voto> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Voto v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Voto> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Voto.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Voto _nullMarshalValue = new Voto();

    /** @hidden */
    public static final long serialVersionUID = -1742148521419468162L;
}
