//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `Votacion.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Votacion;

/** @hidden */
public class _EleccionesPrxI extends com.zeroc.Ice._ObjectPrxI implements EleccionesPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
