/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MesaVotacion;

public class MesaVotacion {
    public static void main(String[] args)
    {
        try(com.zeroc.Ice.Communicator communicator = com.zeroc.Ice.Util.initialize(args))
        {
            com.zeroc.Ice.ObjectPrx base = communicator.stringToProxy("Elecciones:default -h x206m02 -p 10009");
            Votacion.EleccionesPrx elecciones = Votacion.EleccionesPrx.checkedCast(base);
            if(elecciones == null)
            {
                throw new Error("Invalid proxy");
            }
            Votacion.Candidato[] candidatos=elecciones.obtenerCandidatos();
            for(Votacion.Candidato candidato: candidatos){
                System.out.println(candidato.id);
                System.out.println(candidato.nombre);
                System.out.println(candidato.partido);
            }
            elecciones.registrarVoto(3,1);

        } catch (Exception e){
            e.printStackTrace();
        }
    }
}